import type { Metadata } from "next";
import { primary, secondary } from "./fonts";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import "swiper/css";
import "swiper/css/pagination";
export const metadata: Metadata = {
  title: "Umah Shanti",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html>
      <body className={`${primary.variable} ${secondary.variable} antialiased`}>
        <main className="min-h-screen">{children}</main>
        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}
